package com.app.MavenSpringBootMvcAopRestApiOnlineShoppingWithAngular6AndMongodb.repository;

import org.springframework.data.mongodb.repository.MongoRepository;
import org.springframework.stereotype.Repository;
import com.app.MavenSpringBootMvcAopRestApiOnlineShoppingWithAngular6AndMongodb.modal.OrderProduct;
import com.app.MavenSpringBootMvcAopRestApiOnlineShoppingWithAngular6AndMongodb.modal.OrderProductPK;

@Repository
public interface OrderProductRepository extends MongoRepository<OrderProduct, OrderProductPK> {
}
